// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cluster.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Status int32

const (
	Status_OK           Status = 0
	Status_UNAUTHORIZED Status = 1
	Status_ERROR        Status = 2
)

var Status_name = map[int32]string{
	0: "OK",
	1: "UNAUTHORIZED",
	2: "ERROR",
}

var Status_value = map[string]int32{
	"OK":           0,
	"UNAUTHORIZED": 1,
	"ERROR":        2,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{0}
}

type JoinRequest struct {
	JoinToken            string   `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{0}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetJoinToken() string {
	if m != nil {
		return m.JoinToken
	}
	return ""
}

type JoinResponse struct {
	// Information that the joining node should adopt.
	AdvertiseAddr string `protobuf:"bytes,1,opt,name=advertise_addr,json=advertiseAddr,proto3" json:"advertise_addr,omitempty"`
	Id            string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata about the node to join.
	RaftPort    uint32 `protobuf:"varint,3,opt,name=raft_port,json=raftPort,proto3" json:"raft_port,omitempty"`
	SerfPort    uint32 `protobuf:"varint,4,opt,name=serf_port,json=serfPort,proto3" json:"serf_port,omitempty"`
	WanSerfPort uint32 `protobuf:"varint,5,opt,name=wan_serf_port,json=wanSerfPort,proto3" json:"wan_serf_port,omitempty"`
	// Simple status response.
	Status               Status   `protobuf:"varint,6,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *JoinResponse) Reset()         { *m = JoinResponse{} }
func (m *JoinResponse) String() string { return proto.CompactTextString(m) }
func (*JoinResponse) ProtoMessage()    {}
func (*JoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{1}
}

func (m *JoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinResponse.Unmarshal(m, b)
}
func (m *JoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinResponse.Marshal(b, m, deterministic)
}
func (m *JoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinResponse.Merge(m, src)
}
func (m *JoinResponse) XXX_Size() int {
	return xxx_messageInfo_JoinResponse.Size(m)
}
func (m *JoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_JoinResponse proto.InternalMessageInfo

func (m *JoinResponse) GetAdvertiseAddr() string {
	if m != nil {
		return m.AdvertiseAddr
	}
	return ""
}

func (m *JoinResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *JoinResponse) GetRaftPort() uint32 {
	if m != nil {
		return m.RaftPort
	}
	return 0
}

func (m *JoinResponse) GetSerfPort() uint32 {
	if m != nil {
		return m.SerfPort
	}
	return 0
}

func (m *JoinResponse) GetWanSerfPort() uint32 {
	if m != nil {
		return m.WanSerfPort
	}
	return 0
}

func (m *JoinResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type ConfirmJoinRequest struct {
	// Information about our node so that the store knows what we are.
	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RaftAddr string `protobuf:"bytes,2,opt,name=raft_addr,json=raftAddr,proto3" json:"raft_addr,omitempty"`
	// Ensure we authenticate the request.
	JoinToken            string   `protobuf:"bytes,3,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmJoinRequest) Reset()         { *m = ConfirmJoinRequest{} }
func (m *ConfirmJoinRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmJoinRequest) ProtoMessage()    {}
func (*ConfirmJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{2}
}

func (m *ConfirmJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmJoinRequest.Unmarshal(m, b)
}
func (m *ConfirmJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmJoinRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmJoinRequest.Merge(m, src)
}
func (m *ConfirmJoinRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmJoinRequest.Size(m)
}
func (m *ConfirmJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmJoinRequest proto.InternalMessageInfo

func (m *ConfirmJoinRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ConfirmJoinRequest) GetRaftAddr() string {
	if m != nil {
		return m.RaftAddr
	}
	return ""
}

func (m *ConfirmJoinRequest) GetJoinToken() string {
	if m != nil {
		return m.JoinToken
	}
	return ""
}

type ConfirmJoinResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmJoinResponse) Reset()         { *m = ConfirmJoinResponse{} }
func (m *ConfirmJoinResponse) String() string { return proto.CompactTextString(m) }
func (*ConfirmJoinResponse) ProtoMessage()    {}
func (*ConfirmJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{3}
}

func (m *ConfirmJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmJoinResponse.Unmarshal(m, b)
}
func (m *ConfirmJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmJoinResponse.Marshal(b, m, deterministic)
}
func (m *ConfirmJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmJoinResponse.Merge(m, src)
}
func (m *ConfirmJoinResponse) XXX_Size() int {
	return xxx_messageInfo_ConfirmJoinResponse.Size(m)
}
func (m *ConfirmJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmJoinResponse proto.InternalMessageInfo

func (m *ConfirmJoinResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type ApplyRequest struct {
	Body                 []byte   `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyRequest) Reset()         { *m = ApplyRequest{} }
func (m *ApplyRequest) String() string { return proto.CompactTextString(m) }
func (*ApplyRequest) ProtoMessage()    {}
func (*ApplyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{4}
}

func (m *ApplyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyRequest.Unmarshal(m, b)
}
func (m *ApplyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyRequest.Marshal(b, m, deterministic)
}
func (m *ApplyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyRequest.Merge(m, src)
}
func (m *ApplyRequest) XXX_Size() int {
	return xxx_messageInfo_ApplyRequest.Size(m)
}
func (m *ApplyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyRequest proto.InternalMessageInfo

func (m *ApplyRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type ApplyResponse struct {
	Status               Status   `protobuf:"varint,1,opt,name=status,proto3,enum=proto.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplyResponse) Reset()         { *m = ApplyResponse{} }
func (m *ApplyResponse) String() string { return proto.CompactTextString(m) }
func (*ApplyResponse) ProtoMessage()    {}
func (*ApplyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3cfb3b8ec240c376, []int{5}
}

func (m *ApplyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplyResponse.Unmarshal(m, b)
}
func (m *ApplyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplyResponse.Marshal(b, m, deterministic)
}
func (m *ApplyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplyResponse.Merge(m, src)
}
func (m *ApplyResponse) XXX_Size() int {
	return xxx_messageInfo_ApplyResponse.Size(m)
}
func (m *ApplyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ApplyResponse proto.InternalMessageInfo

func (m *ApplyResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func init() {
	proto.RegisterEnum("proto.Status", Status_name, Status_value)
	proto.RegisterType((*JoinRequest)(nil), "proto.JoinRequest")
	proto.RegisterType((*JoinResponse)(nil), "proto.JoinResponse")
	proto.RegisterType((*ConfirmJoinRequest)(nil), "proto.ConfirmJoinRequest")
	proto.RegisterType((*ConfirmJoinResponse)(nil), "proto.ConfirmJoinResponse")
	proto.RegisterType((*ApplyRequest)(nil), "proto.ApplyRequest")
	proto.RegisterType((*ApplyResponse)(nil), "proto.ApplyResponse")
}

func init() { proto.RegisterFile("cluster.proto", fileDescriptor_3cfb3b8ec240c376) }

var fileDescriptor_3cfb3b8ec240c376 = []byte{
	// 396 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x90, 0xdf, 0x8a, 0xd3, 0x40,
	0x18, 0xc5, 0x77, 0xd2, 0x26, 0x98, 0xaf, 0x49, 0x09, 0xdf, 0x7a, 0x11, 0x23, 0x42, 0x09, 0x2c,
	0x14, 0xd1, 0x05, 0x57, 0xf1, 0xca, 0x9b, 0xb2, 0xae, 0xf8, 0x07, 0xec, 0x32, 0x6d, 0x6f, 0xbc,
	0x89, 0xa9, 0x33, 0x85, 0x68, 0xcd, 0xc4, 0x99, 0xa9, 0xa5, 0x2f, 0xe6, 0x43, 0xf8, 0x54, 0x92,
	0x99, 0xa4, 0x26, 0x56, 0x04, 0xaf, 0x12, 0x7e, 0xe7, 0xcc, 0xcc, 0x39, 0x07, 0xc2, 0x4f, 0xdb,
	0x9d, 0xd2, 0x5c, 0x5e, 0x56, 0x52, 0x68, 0x81, 0xae, 0xf9, 0xa4, 0x8f, 0x60, 0xf4, 0x56, 0x14,
	0x25, 0xe5, 0xdf, 0x76, 0x5c, 0x69, 0x7c, 0x00, 0xf0, 0x59, 0x14, 0x65, 0xa6, 0xc5, 0x17, 0x5e,
	0xc6, 0x64, 0x42, 0xa6, 0x3e, 0xf5, 0x6b, 0xb2, 0xac, 0x41, 0xfa, 0x93, 0x40, 0x60, 0xed, 0xaa,
	0x12, 0xa5, 0xe2, 0x78, 0x01, 0xe3, 0x9c, 0x7d, 0xe7, 0x52, 0x17, 0x8a, 0x67, 0x39, 0x63, 0xb2,
	0x39, 0x13, 0x1e, 0xe9, 0x8c, 0x31, 0x89, 0x63, 0x70, 0x0a, 0x16, 0x3b, 0x46, 0x72, 0x0a, 0x86,
	0xf7, 0xc1, 0x97, 0xf9, 0x46, 0x67, 0x95, 0x90, 0x3a, 0x1e, 0x4c, 0xc8, 0x34, 0xa4, 0x77, 0x6a,
	0x70, 0x2b, 0xa4, 0xae, 0x45, 0xc5, 0xe5, 0xc6, 0x8a, 0x43, 0x2b, 0xd6, 0xc0, 0x88, 0x29, 0x84,
	0xfb, 0xbc, 0xcc, 0x7e, 0x1b, 0x5c, 0x63, 0x18, 0xed, 0xf3, 0x72, 0xd1, 0x7a, 0x2e, 0xc0, 0x53,
	0x3a, 0xd7, 0x3b, 0x15, 0x7b, 0x13, 0x32, 0x1d, 0x5f, 0x85, 0xb6, 0xf2, 0xe5, 0xc2, 0x40, 0xda,
	0x88, 0xe9, 0x47, 0xc0, 0x6b, 0x51, 0x6e, 0x0a, 0xf9, 0xb5, 0xbb, 0x80, 0x8d, 0x4a, 0x4e, 0xa2,
	0x9a, 0x72, 0xb6, 0x81, 0x89, 0x6a, 0x7a, 0xf5, 0xe7, 0x1a, 0xfc, 0x39, 0xd7, 0x0b, 0x38, 0xef,
	0xbd, 0x70, 0x1c, 0xad, 0xcd, 0x47, 0xfe, 0x95, 0x2f, 0x85, 0x60, 0x56, 0x55, 0xdb, 0x43, 0x9b,
	0x0c, 0x61, 0xb8, 0x16, 0xec, 0x60, 0x0e, 0x05, 0xd4, 0xfc, 0xa7, 0xcf, 0x21, 0x6c, 0x3c, 0xff,
	0x75, 0xf7, 0xc3, 0xc7, 0xe0, 0x59, 0x82, 0x1e, 0x38, 0xf3, 0x77, 0xd1, 0x19, 0x46, 0x10, 0xac,
	0xde, 0xcf, 0x56, 0xcb, 0xd7, 0x73, 0xfa, 0xe6, 0xc3, 0xcd, 0xcb, 0x88, 0xa0, 0x0f, 0xee, 0x0d,
	0xa5, 0x73, 0x1a, 0x39, 0x57, 0x3f, 0x08, 0x0c, 0xe8, 0xed, 0x35, 0x3e, 0x81, 0x61, 0xdd, 0x04,
	0xb1, 0xb9, 0xb5, 0x33, 0x5c, 0x72, 0xde, 0x63, 0x36, 0x4e, 0x7a, 0x86, 0xaf, 0x60, 0xd4, 0xd9,
	0x00, 0xef, 0x35, 0xae, 0xd3, 0xe5, 0x93, 0xe4, 0x6f, 0xd2, 0xf1, 0x9e, 0x67, 0xe0, 0x9a, 0xa6,
	0xd8, 0xbe, 0xd3, 0xdd, 0x26, 0xb9, 0xdb, 0x87, 0xed, 0xa9, 0xb5, 0x67, 0xf0, 0xd3, 0x5f, 0x01,
	0x00, 0x00, 0xff, 0xff, 0x7f, 0x82, 0xef, 0x0a, 0xfd, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RPCClient is the client API for RPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RPCClient interface {
	// Cluster join and confirm join operations.
	Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error)
	ConfirmJoin(ctx context.Context, in *ConfirmJoinRequest, opts ...grpc.CallOption) (*ConfirmJoinResponse, error)
	// Apply is used for leader forwarding.
	Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error)
}

type rPCClient struct {
	cc *grpc.ClientConn
}

func NewRPCClient(cc *grpc.ClientConn) RPCClient {
	return &rPCClient{cc}
}

func (c *rPCClient) Join(ctx context.Context, in *JoinRequest, opts ...grpc.CallOption) (*JoinResponse, error) {
	out := new(JoinResponse)
	err := c.cc.Invoke(ctx, "/proto.RPC/Join", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) ConfirmJoin(ctx context.Context, in *ConfirmJoinRequest, opts ...grpc.CallOption) (*ConfirmJoinResponse, error) {
	out := new(ConfirmJoinResponse)
	err := c.cc.Invoke(ctx, "/proto.RPC/ConfirmJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rPCClient) Apply(ctx context.Context, in *ApplyRequest, opts ...grpc.CallOption) (*ApplyResponse, error) {
	out := new(ApplyResponse)
	err := c.cc.Invoke(ctx, "/proto.RPC/Apply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RPCServer is the server API for RPC service.
type RPCServer interface {
	// Cluster join and confirm join operations.
	Join(context.Context, *JoinRequest) (*JoinResponse, error)
	ConfirmJoin(context.Context, *ConfirmJoinRequest) (*ConfirmJoinResponse, error)
	// Apply is used for leader forwarding.
	Apply(context.Context, *ApplyRequest) (*ApplyResponse, error)
}

func RegisterRPCServer(s *grpc.Server, srv RPCServer) {
	s.RegisterService(&_RPC_serviceDesc, srv)
}

func _RPC_Join_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Join(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RPC/Join",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Join(ctx, req.(*JoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_ConfirmJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).ConfirmJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RPC/ConfirmJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).ConfirmJoin(ctx, req.(*ConfirmJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RPC_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RPCServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.RPC/Apply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RPCServer).Apply(ctx, req.(*ApplyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _RPC_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.RPC",
	HandlerType: (*RPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Join",
			Handler:    _RPC_Join_Handler,
		},
		{
			MethodName: "ConfirmJoin",
			Handler:    _RPC_ConfirmJoin_Handler,
		},
		{
			MethodName: "Apply",
			Handler:    _RPC_Apply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cluster.proto",
}
