// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ClusterJoinStatus int32

const (
	ClusterJoinStatus_ACCEPTED     ClusterJoinStatus = 0
	ClusterJoinStatus_UNAUTHORIZED ClusterJoinStatus = 1
)

var ClusterJoinStatus_name = map[int32]string{
	0: "ACCEPTED",
	1: "UNAUTHORIZED",
}

var ClusterJoinStatus_value = map[string]int32{
	"ACCEPTED":     0,
	"UNAUTHORIZED": 1,
}

func (x ClusterJoinStatus) String() string {
	return proto.EnumName(ClusterJoinStatus_name, int32(x))
}

func (ClusterJoinStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type ClusterJoinRequest struct {
	JoinToken            string   `protobuf:"bytes,1,opt,name=join_token,json=joinToken,proto3" json:"join_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClusterJoinRequest) Reset()         { *m = ClusterJoinRequest{} }
func (m *ClusterJoinRequest) String() string { return proto.CompactTextString(m) }
func (*ClusterJoinRequest) ProtoMessage()    {}
func (*ClusterJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *ClusterJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterJoinRequest.Unmarshal(m, b)
}
func (m *ClusterJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterJoinRequest.Marshal(b, m, deterministic)
}
func (m *ClusterJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterJoinRequest.Merge(m, src)
}
func (m *ClusterJoinRequest) XXX_Size() int {
	return xxx_messageInfo_ClusterJoinRequest.Size(m)
}
func (m *ClusterJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterJoinRequest proto.InternalMessageInfo

func (m *ClusterJoinRequest) GetJoinToken() string {
	if m != nil {
		return m.JoinToken
	}
	return ""
}

type ClusterJoinResponse struct {
	// Information that the joining node should adopt.
	AdvertiseIp string `protobuf:"bytes,1,opt,name=advertise_ip,json=advertiseIp,proto3" json:"advertise_ip,omitempty"`
	Id          string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Metadata about the node to join.
	RaftPort    uint32 `protobuf:"varint,3,opt,name=raft_port,json=raftPort,proto3" json:"raft_port,omitempty"`
	SerfPort    uint32 `protobuf:"varint,4,opt,name=serf_port,json=serfPort,proto3" json:"serf_port,omitempty"`
	WanSerfPort uint32 `protobuf:"varint,5,opt,name=wan_serf_port,json=wanSerfPort,proto3" json:"wan_serf_port,omitempty"`
	// Simple status response.
	JoinStatus           ClusterJoinStatus `protobuf:"varint,6,opt,name=join_status,json=joinStatus,proto3,enum=rpc.ClusterJoinStatus" json:"join_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ClusterJoinResponse) Reset()         { *m = ClusterJoinResponse{} }
func (m *ClusterJoinResponse) String() string { return proto.CompactTextString(m) }
func (*ClusterJoinResponse) ProtoMessage()    {}
func (*ClusterJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *ClusterJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClusterJoinResponse.Unmarshal(m, b)
}
func (m *ClusterJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClusterJoinResponse.Marshal(b, m, deterministic)
}
func (m *ClusterJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClusterJoinResponse.Merge(m, src)
}
func (m *ClusterJoinResponse) XXX_Size() int {
	return xxx_messageInfo_ClusterJoinResponse.Size(m)
}
func (m *ClusterJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ClusterJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ClusterJoinResponse proto.InternalMessageInfo

func (m *ClusterJoinResponse) GetAdvertiseIp() string {
	if m != nil {
		return m.AdvertiseIp
	}
	return ""
}

func (m *ClusterJoinResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *ClusterJoinResponse) GetRaftPort() uint32 {
	if m != nil {
		return m.RaftPort
	}
	return 0
}

func (m *ClusterJoinResponse) GetSerfPort() uint32 {
	if m != nil {
		return m.SerfPort
	}
	return 0
}

func (m *ClusterJoinResponse) GetWanSerfPort() uint32 {
	if m != nil {
		return m.WanSerfPort
	}
	return 0
}

func (m *ClusterJoinResponse) GetJoinStatus() ClusterJoinStatus {
	if m != nil {
		return m.JoinStatus
	}
	return ClusterJoinStatus_ACCEPTED
}

func init() {
	proto.RegisterEnum("rpc.ClusterJoinStatus", ClusterJoinStatus_name, ClusterJoinStatus_value)
	proto.RegisterType((*ClusterJoinRequest)(nil), "rpc.ClusterJoinRequest")
	proto.RegisterType((*ClusterJoinResponse)(nil), "rpc.ClusterJoinResponse")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 294 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4f, 0xf2, 0x30,
	0x18, 0xc7, 0x29, 0xbc, 0x2f, 0xb2, 0x67, 0x40, 0xb0, 0x26, 0xba, 0x68, 0x4c, 0xe6, 0x4e, 0x8b,
	0x07, 0x0e, 0xec, 0xe0, 0x19, 0xc7, 0x12, 0x31, 0x51, 0xc9, 0x18, 0x17, 0x2f, 0xcb, 0x64, 0x25,
	0xa9, 0x9a, 0xb6, 0xb6, 0x9d, 0x7c, 0x5c, 0xbf, 0x8a, 0x69, 0x37, 0x15, 0xe5, 0xd6, 0xfc, 0x7e,
	0xff, 0x7f, 0xda, 0xe7, 0x29, 0x38, 0x52, 0xac, 0xc7, 0x42, 0x72, 0xcd, 0x71, 0x47, 0x8a, 0x75,
	0x10, 0x01, 0x8e, 0x5f, 0x2b, 0xa5, 0x89, 0xbc, 0xe5, 0x94, 0xa5, 0xe4, 0xad, 0x22, 0x4a, 0xe3,
	0x73, 0x80, 0x67, 0x4e, 0x59, 0xae, 0xf9, 0x0b, 0x61, 0x1e, 0xf2, 0x51, 0xe8, 0xa4, 0x8e, 0x21,
	0x99, 0x01, 0xc1, 0x07, 0x82, 0xa3, 0x5f, 0x2d, 0x25, 0x38, 0x53, 0x04, 0x5f, 0x40, 0xbf, 0x28,
	0xdf, 0x89, 0xd4, 0x54, 0x91, 0x9c, 0x8a, 0xa6, 0xe8, 0x7e, 0xb3, 0xb9, 0xc0, 0x43, 0x68, 0xd3,
	0xd2, 0x6b, 0x5b, 0xd1, 0xa6, 0x25, 0x3e, 0x03, 0x47, 0x16, 0x1b, 0x9d, 0x0b, 0x2e, 0xb5, 0xd7,
	0xf1, 0x51, 0x38, 0x48, 0x7b, 0x06, 0x2c, 0xb8, 0xd4, 0x46, 0x2a, 0x22, 0x37, 0xb5, 0xfc, 0x57,
	0x4b, 0x03, 0xac, 0x0c, 0x60, 0xb0, 0x2d, 0x58, 0xfe, 0x13, 0xf8, 0x6f, 0x03, 0xee, 0xb6, 0x60,
	0xcb, 0xaf, 0xcc, 0x15, 0xb8, 0x76, 0x0e, 0xa5, 0x0b, 0x5d, 0x29, 0xaf, 0xeb, 0xa3, 0x70, 0x38,
	0x39, 0x1e, 0x9b, 0x1d, 0xec, 0xbc, 0x7f, 0x69, 0x6d, 0x6a, 0x47, 0xae, 0xcf, 0x97, 0x11, 0x1c,
	0xee, 0x05, 0x70, 0x1f, 0x7a, 0xd3, 0x38, 0x4e, 0x16, 0x59, 0x32, 0x1b, 0xb5, 0xf0, 0x08, 0xfa,
	0xab, 0xfb, 0xe9, 0x2a, 0xbb, 0x79, 0x48, 0xe7, 0x8f, 0xc9, 0x6c, 0x84, 0x26, 0x77, 0x70, 0xd0,
	0x94, 0xf0, 0x35, 0xb8, 0x3b, 0x7d, 0x7c, 0xf2, 0xf7, 0xca, 0x66, 0xd1, 0xa7, 0xde, 0xbe, 0xa8,
	0x77, 0x19, 0xb4, 0x9e, 0xba, 0xf6, 0x9b, 0xa2, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0a, 0xff,
	0x19, 0xa6, 0xb3, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClusterClient is the client API for Cluster service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClusterClient interface {
	ClusterJoin(ctx context.Context, in *ClusterJoinRequest, opts ...grpc.CallOption) (*ClusterJoinResponse, error)
}

type clusterClient struct {
	cc *grpc.ClientConn
}

func NewClusterClient(cc *grpc.ClientConn) ClusterClient {
	return &clusterClient{cc}
}

func (c *clusterClient) ClusterJoin(ctx context.Context, in *ClusterJoinRequest, opts ...grpc.CallOption) (*ClusterJoinResponse, error) {
	out := new(ClusterJoinResponse)
	err := c.cc.Invoke(ctx, "/rpc.Cluster/ClusterJoin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClusterServer is the server API for Cluster service.
type ClusterServer interface {
	ClusterJoin(context.Context, *ClusterJoinRequest) (*ClusterJoinResponse, error)
}

func RegisterClusterServer(s *grpc.Server, srv ClusterServer) {
	s.RegisterService(&_Cluster_serviceDesc, srv)
}

func _Cluster_ClusterJoin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterJoinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClusterServer).ClusterJoin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Cluster/ClusterJoin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClusterServer).ClusterJoin(ctx, req.(*ClusterJoinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cluster_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Cluster",
	HandlerType: (*ClusterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ClusterJoin",
			Handler:    _Cluster_ClusterJoin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc.proto",
}
